INSERT INTO TOURNAMENTS
(ATP_TOUR_ID, TENNIS_TV_ID, NAME, POINTS, LOCATION, SURFACE, `YEAR`, START_DATE, END_DATE)
VALUES(123, 123, 'FIRST_TOURNAMENT', 1000, 'A_LOCATION', 'HARD', 2025, '2025-01-01', '2025-01-07');
INSERT INTO TOURNAMENTS
(ATP_TOUR_ID, TENNIS_TV_ID, NAME, POINTS, LOCATION, SURFACE, `YEAR`, START_DATE, END_DATE)
VALUES(456, 456, 'SECOND_TOURNAMENT', 250, 'ANOTHER_LOCATION', 'CLAY', 2025, '2025-01-08', '2025-01-14');
INSERT INTO TOURNAMENTS
(ATP_TOUR_ID, TENNIS_TV_ID, NAME, POINTS, LOCATION, SURFACE, `YEAR`, START_DATE, END_DATE)
VALUES(789, 789, 'THIRD_TOURNAMENT', 500, 'THIRD_LOCATION', 'GRASS', 2025, '2025-01-15', '2025-01-21');
INSERT INTO TOURNAMENTS
(ATP_TOUR_ID, TENNIS_TV_ID, NAME, POINTS, LOCATION, SURFACE, `YEAR`, START_DATE, END_DATE)
VALUES(012, 012, 'FOURTH_TOURNAMENT', 250, 'FOURTH_LOCATION', 'HARD', 2025, '2025-01-22', '2025-01-28');

INSERT INTO TOURNAMENTS
(ATP_TOUR_ID, TENNIS_TV_ID, NAME, POINTS, LOCATION, SURFACE, `YEAR`, START_DATE, END_DATE)
VALUES(123, 123, 'FIRST_TOURNAMENT', 1000, 'A_LOCATION', 'HARD', 2026, '2026-01-01', '2026-01-07');
INSERT INTO TOURNAMENTS
(ATP_TOUR_ID, TENNIS_TV_ID, NAME, POINTS, LOCATION, SURFACE, `YEAR`, START_DATE, END_DATE)
VALUES(456, 456, 'SECOND_TOURNAMENT', 250, 'ANOTHER_LOCATION', 'CLAY', 2026, '2026-01-08', '2026-01-14');
INSERT INTO TOURNAMENTS
(ATP_TOUR_ID, TENNIS_TV_ID, NAME, POINTS, LOCATION, SURFACE, `YEAR`, START_DATE, END_DATE)
VALUES(789, 789, 'THIRD_TOURNAMENT', 500, 'THIRD_LOCATION', 'GRASS', 2026, '2026-01-15', '2026-01-21');
INSERT INTO TOURNAMENTS
(ATP_TOUR_ID, TENNIS_TV_ID, NAME, POINTS, LOCATION, SURFACE, `YEAR`, START_DATE, END_DATE)
VALUES(012, 012, 'FOURTH_TOURNAMENT', 250, 'FOURTH_LOCATION', 'HARD', 2026, '2026-01-22', '2026-01-28');


INSERT INTO FANTA_TOURNAMENTS (STARTING_TOURNAMENT, ENDING_TOURNAMENT, TOURNAMENT_YEAR) VALUES(1, 3, 2025);
INSERT INTO FANTA_TOURNAMENTS (STARTING_TOURNAMENT, ENDING_TOURNAMENT, TOURNAMENT_YEAR) VALUES(2, 3, 2025);

INSERT INTO FANTA_TOURNAMENTS (STARTING_TOURNAMENT, ENDING_TOURNAMENT, TOURNAMENT_YEAR) VALUES(1, 4, 2026);


-- 2025 teams
INSERT INTO FANTA_TEAMS (OWNER_ID) VALUES('AN_OWNER');
INSERT INTO FANTA_TEAMS (OWNER_ID) VALUES('ANOTHER_OWNER');
INSERT INTO FANTA_TEAMS (OWNER_ID) VALUES('THIRD_OWNER');
INSERT INTO FANTA_TEAMS (OWNER_ID) VALUES('FOURTH_OWNER');
INSERT INTO FANTA_TEAMS (OWNER_ID) VALUES('FIFTH_OWNER');
-- 2026 teams
INSERT INTO FANTA_TEAMS (OWNER_ID) VALUES('ANOTHER_OWNER');
INSERT INTO FANTA_TEAMS (OWNER_ID) VALUES('FIFTH_OWNER');
INSERT INTO FANTA_TEAMS (OWNER_ID) VALUES('SIXTH_OWNER');

ALTER TABLE FANTA_TOURNAMENTS_TEAMS ADD CONSTRAINT UNIQUE_FANTA_TOURNAMENT UNIQUE (FANTA_TOURNAMENT_ID);

INSERT INTO FANTA_TOURNAMENTS_TEAMS (FANTA_TOURNAMENT_ID, TEAM_ID) VALUES(1, 1);
INSERT INTO FANTA_TOURNAMENTS_TEAMS (FANTA_TOURNAMENT_ID, TEAM_ID) VALUES(2, 4);

INSERT INTO FANTA_TOURNAMENTS_TEAMS (FANTA_TOURNAMENT_ID, TEAM_ID) VALUES(3, 2);