SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE TEAMS;
TRUNCATE TABLE PLAYERS_POINTS;
TRUNCATE TABLE TOURNAMENTS;
TRUNCATE TABLE PLAYERS;
TRUNCATE TABLE FANTA_TOURNAMENTS_TEAMS;
TRUNCATE TABLE FANTA_TEAMS;
TRUNCATE TABLE FANTA_TOURNAMENTS;

SET FOREIGN_KEY_CHECKS = 1;
