-- fanta_tennis.FANTA_TOURNAMENTS definition
DROP TABLE IF EXISTS FANTA_TOURNAMENTS;

CREATE TABLE `FANTA_TOURNAMENTS` (
  `FANTA_TOURNAMENT_ID` int NOT NULL AUTO_INCREMENT,
  `STARTING_TOURNAMENT` int NOT NULL,
  `ENDING_TOURNAMENT` int NOT NULL,
  `TOURNAMENT_YEAR` int NOT NULL,
  PRIMARY KEY (`FANTA_TOURNAMENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;