INSERT INTO TOURNAMENTS
(ATP_TOUR_ID, TENNIS_TV_ID, NAME, POINTS, LOCATION, SURFACE, `YEAR`, START_DATE, END_DATE)
VALUES(123, 123, 'FIRST_TOURNAMENT', 1000, 'A_LOCATION', 'HARD', 2025, '2025-01-01', '2025-01-07');
INSERT INTO TOURNAMENTS
(ATP_TOUR_ID, TENNIS_TV_ID, NAME, POINTS, LOCATION, SURFACE, `YEAR`, START_DATE, END_DATE)
VALUES(456, 456, 'SECOND_TOURNAMENT', 250, 'ANOTHER_LOCATION', 'CLAY', 2025, '2025-01-08', '2025-01-14');
INSERT INTO TOURNAMENTS
(ATP_TOUR_ID, TENNIS_TV_ID, NAME, POINTS, LOCATION, SURFACE, `YEAR`, START_DATE, END_DATE)
VALUES(789, 789, 'THIRD_TOURNAMENT', 500, 'THIRD_LOCATION', 'GRASS', 2025, '2025-01-15', '2025-01-21');
INSERT INTO TOURNAMENTS
(ATP_TOUR_ID, TENNIS_TV_ID, NAME, POINTS, LOCATION, SURFACE, `YEAR`, START_DATE, END_DATE)
VALUES(012, 012, 'FOURTH_TOURNAMENT', 250, 'FOURTH_LOCATION', 'HARD', 2025, '2025-01-22', '2025-01-28');

INSERT INTO TOURNAMENTS
(ATP_TOUR_ID, TENNIS_TV_ID, NAME, POINTS, LOCATION, SURFACE, `YEAR`, START_DATE, END_DATE)
VALUES(123, 123, 'FIRST_TOURNAMENT', 1000, 'A_LOCATION', 'HARD', 2026, '2026-01-01', '2026-01-07');
INSERT INTO TOURNAMENTS
(ATP_TOUR_ID, TENNIS_TV_ID, NAME, POINTS, LOCATION, SURFACE, `YEAR`, START_DATE, END_DATE)
VALUES(456, 456, 'SECOND_TOURNAMENT', 250, 'ANOTHER_LOCATION', 'CLAY', 2026, '2026-01-08', '2026-01-14');
INSERT INTO TOURNAMENTS
(ATP_TOUR_ID, TENNIS_TV_ID, NAME, POINTS, LOCATION, SURFACE, `YEAR`, START_DATE, END_DATE)
VALUES(789, 789, 'THIRD_TOURNAMENT', 500, 'THIRD_LOCATION', 'GRASS', 2026, '2026-01-15', '2026-01-21');
INSERT INTO TOURNAMENTS
(ATP_TOUR_ID, TENNIS_TV_ID, NAME, POINTS, LOCATION, SURFACE, `YEAR`, START_DATE, END_DATE)
VALUES(012, 012, 'FOURTH_TOURNAMENT', 250, 'FOURTH_LOCATION', 'HARD', 2026, '2026-01-22', '2026-01-28');


INSERT INTO FANTA_TOURNAMENTS (STARTING_TOURNAMENT, ENDING_TOURNAMENT, TOURNAMENT_YEAR) VALUES(1, 3, 2025);
INSERT INTO FANTA_TOURNAMENTS (STARTING_TOURNAMENT, ENDING_TOURNAMENT, TOURNAMENT_YEAR) VALUES(2, 3, 2025);

INSERT INTO FANTA_TOURNAMENTS (STARTING_TOURNAMENT, ENDING_TOURNAMENT, TOURNAMENT_YEAR) VALUES(1, 4, 2026);


-- 2025 teams
INSERT INTO FANTA_TEAMS (OWNER_ID) VALUES('AN_OWNER');
INSERT INTO FANTA_TEAMS (OWNER_ID) VALUES('ANOTHER_OWNER');
INSERT INTO FANTA_TEAMS (OWNER_ID) VALUES('THIRD_OWNER');
INSERT INTO FANTA_TEAMS (OWNER_ID) VALUES('FOURTH_OWNER');
INSERT INTO FANTA_TEAMS (OWNER_ID) VALUES('FIFTH_OWNER');
-- 2026 teams
INSERT INTO FANTA_TEAMS (OWNER_ID) VALUES('ANOTHER_OWNER');
INSERT INTO FANTA_TEAMS (OWNER_ID) VALUES('FIFTH_OWNER');
INSERT INTO FANTA_TEAMS (OWNER_ID) VALUES('SIXTH_OWNER');


INSERT INTO FANTA_TOURNAMENTS_TEAMS (FANTA_TOURNAMENT_ID, TEAM_ID) VALUES(1, 1);
INSERT INTO FANTA_TOURNAMENTS_TEAMS (FANTA_TOURNAMENT_ID, TEAM_ID) VALUES(1, 2);
INSERT INTO FANTA_TOURNAMENTS_TEAMS (FANTA_TOURNAMENT_ID, TEAM_ID) VALUES(1, 3);
INSERT INTO FANTA_TOURNAMENTS_TEAMS (FANTA_TOURNAMENT_ID, TEAM_ID) VALUES(2, 4);
INSERT INTO FANTA_TOURNAMENTS_TEAMS (FANTA_TOURNAMENT_ID, TEAM_ID) VALUES(2, 5);

INSERT INTO FANTA_TOURNAMENTS_TEAMS (FANTA_TOURNAMENT_ID, TEAM_ID) VALUES(3, 6);
INSERT INTO FANTA_TOURNAMENTS_TEAMS (FANTA_TOURNAMENT_ID, TEAM_ID) VALUES(3, 7);
INSERT INTO FANTA_TOURNAMENTS_TEAMS (FANTA_TOURNAMENT_ID, TEAM_ID) VALUES(3, 8);


INSERT INTO PLAYERS (PLAYER_ID, ATP_TOUR_ID, FULL_NAME) VALUES('A0B1', 'A0B1', 'AAA BBB');
INSERT INTO PLAYERS (PLAYER_ID, ATP_TOUR_ID, FULL_NAME) VALUES('C0D1', 'C0D1', 'CCC DDD');
INSERT INTO PLAYERS (PLAYER_ID, ATP_TOUR_ID, FULL_NAME) VALUES('E2F8', 'E2F8', 'EEE FFF');
INSERT INTO PLAYERS (PLAYER_ID, ATP_TOUR_ID, FULL_NAME) VALUES('GH00', 'GH00', 'GGG HHH');
INSERT INTO PLAYERS (PLAYER_ID, ATP_TOUR_ID, FULL_NAME) VALUES('I0J7', 'I0J7', 'III JJJ');
INSERT INTO PLAYERS (PLAYER_ID, ATP_TOUR_ID, FULL_NAME) VALUES('K5L8', 'K5L8', 'KKK LLL');
INSERT INTO PLAYERS (PLAYER_ID, ATP_TOUR_ID, FULL_NAME) VALUES('MN98', 'MN98', 'MMM NNN');
INSERT INTO PLAYERS (PLAYER_ID, ATP_TOUR_ID, FULL_NAME) VALUES('O7P6', 'O7P6', 'OOO PPP');
INSERT INTO PLAYERS (PLAYER_ID, ATP_TOUR_ID, FULL_NAME) VALUES('QR43', 'QR43', 'QQQ RRR');
INSERT INTO PLAYERS (PLAYER_ID, ATP_TOUR_ID, FULL_NAME) VALUES('S7T5', 'S7T5', 'SSS TTT');


INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 1, 'A0B1', 0.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 1, 'C0D1', 1.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 1, 'E2F8', 2.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 1, 'GH00', 4.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 1, 'I0J7', 4.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 1, 'K5L8', 16.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 1, 'MN98', 0.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 1, 'O7P6', 32.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 1, 'QR43', 40.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 1, 'S7T5', 2.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 2, 'A0B1', 8.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 2, 'C0D1', 2.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 2, 'E2F8', 0.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 2, 'GH00', 1.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 2, 'I0J7', 1.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 2, 'K5L8', 10.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 2, 'MN98', 2.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 2, 'O7P6', 4.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 2, 'QR43', 0.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 2, 'S7T5', 8.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 3, 'A0B1', 4.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 3, 'C0D1', 4.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 3, 'E2F8', 2.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 3, 'GH00', 1.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 3, 'I0J7', 0.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 3, 'K5L8', 8.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 3, 'MN98', 0.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 3, 'O7P6', 2.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 3, 'QR43', 1.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 3, 'S7T5', 4.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 4, 'A0B1', 2.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 4, 'C0D1', 0.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 4, 'E2F8', 1.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 4, 'GH00', 1.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 4, 'I0J7', 2.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 4, 'K5L8', 4.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 4, 'MN98', 10.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 4, 'O7P6', 1.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 4, 'QR43', 0.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2025, 4, 'S7T5', 8.00);

INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2026, 1, 'A0B1', 4.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2026, 1, 'C0D1', 2.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2026, 1, 'E2F8', 0.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2026, 1, 'GH00', 1.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2026, 1, 'I0J7', 1.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2026, 1, 'K5L8', 32.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2026, 1, 'MN98', 8.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2026, 1, 'O7P6', 0.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2026, 1, 'QR43', 2.00);
INSERT INTO PLAYERS_POINTS (TOURNAMENT_YEAR, TOURNAMENT_ID, PLAYER_ID, FANTA_POINTS) VALUES(2026, 1, 'S7T5', 40.00);


INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(1, 'A0B1', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(1, 'MN98', 1, 1);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(1, 'K5L8', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(2, 'C0D1', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(2, 'O7P6', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(2, 'QR43', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(3, 'E2F8', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(3, 'GH00', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(3, 'I0J7', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(1, 'S7T5', 2, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(4, 'S7T5', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(4, 'GH00', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(4, 'C0D1', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(4, 'K5L8', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(5, 'MN98', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(5, 'QR43', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(5, 'E2F8', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(5, 'A0B1', 1, NULL);

INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(6, 'A0B1', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(6, 'E2F8', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(6, 'K5L8', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(7, 'QR43', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(7, 'I0J7', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(7, 'S7T5', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(8, 'MN98', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(8, 'GH00', 1, NULL);
INSERT INTO TEAMS (TEAM_ID, PLAYER_ID, STARTING_TOURNAMENT, ENDING_TOURNAMENT) VALUES(8, 'C0D1', 1, NULL);