/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.posadeus.fantatennis.controller

import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.*

@RestController
interface JobApi {


    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/job/tournaments/{year}"]
    )
    fun addTournamentsForYear( @PathVariable("year") year: Int): ResponseEntity<Unit>


    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/job/points/{tournamentId}/{year}"]
    )
    fun updatePlayersFantaPoints( @PathVariable("tournamentId") tournamentId: Int, @PathVariable("year") year: Int): ResponseEntity<Unit>
}
