/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.posadeus.fantatennis.controller

import com.posadeus.fantatennis.controller.model.player.Player
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.*

@RestController
interface PlayerApi {


    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/player/{id}"],
            produces = ["application/json"]
    )
    fun player( @PathVariable("id") id: Int): ResponseEntity<Player>
}
