/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.posadeus.fantatennis.controller

import com.posadeus.fantatennis.controller.model.ranking.RankedPlayer
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestMethod

@RequestMapping("\${api.base-path:}")
interface RankingApi {


    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/players"],
            produces = ["application/json"]
    )
    fun players(): ResponseEntity<List<RankedPlayer>>
}
