/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.posadeus.fantatennis.controller

import com.posadeus.fantatennis.controller.model.ranking.RankedPlayer
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.*

@RestController
interface RankingApi {


    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/players/ranking/{positions}"],
            produces = ["application/json"]
    )
    fun players( @PathVariable("positions") positions: Int): ResponseEntity<List<RankedPlayer>>
}
