/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.posadeus.fantatennis.controller

import com.posadeus.fantatennis.controller.model.team.TeamDto
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.*

@RequestMapping("\${api.base-path:}")
interface TeamApi {


    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/{userId}/team/{teamId}"],
            produces = ["application/json"]
    )
    fun team( @PathVariable("userId") userId: String, @PathVariable("teamId") teamId: String): ResponseEntity<TeamDto>
}
