/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.posadeus.fantatennis.controller

import com.posadeus.fantatennis.controller.model.team.*
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.*

@RestController
interface TeamApi {


    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/team/{teamId}/players"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun addPlayers( @PathVariable("teamId") teamId: Int, @RequestBody playersToAddDto: PlayersToAddDto): ResponseEntity<TeamDto>


    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/team"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun create( @RequestBody teamToCreateDto: TeamToCreateDto): ResponseEntity<TeamCreatedDto>


    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/team/{teamId}"],
            produces = ["application/json"]
    )
    fun retrieve( @PathVariable("teamId") teamId: Int): ResponseEntity<TeamDto>
}
