/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.posadeus.fantatennis.controller

import com.posadeus.fantatennis.controller.model.tournament.*
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.*

@RestController
interface TournamentApi {


    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/tournament"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun create( @RequestBody tournamentToCreateDto: TournamentToCreateDto): ResponseEntity<TournamentCreatedDto>


    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/tournament/{tournamentId}"],
            produces = ["application/json"]
    )
    fun retrieve( @PathVariable("tournamentId") tournamentId: Int): ResponseEntity<TournamentDto>


    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/tournaments"],
            produces = ["application/json"]
    )
    fun retrieveAll(): ResponseEntity<TournamentsDto>
}
