package com.posadeus.fantatennis.app.configuration.infrastructure.jdbc

import com.posadeus.fantatennis.domain.infrastructure.RetrieveFantaTournamentResultsRepository
import com.posadeus.fantatennis.infrastructure.repository.database.jdbc.JdbcRetrieveFantaTournamentResultsRepository
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate

@Configuration
class RetrieveFantaTournamentResultsRepositoryConfiguration {

  @Bean
  fun jdbcRetrieveFantaTournamentResultsRepository(namedParameterJdbcTemplate: NamedParameterJdbcTemplate): RetrieveFantaTournamentResultsRepository =
      JdbcRetrieveFantaTournamentResultsRepository(namedParameterJdbcTemplate)
}