<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.2.1</version>
  </parent>

  <groupId>com.posadeus</groupId>
  <artifactId>fantatennis</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <kotlin.code.style>obsolete</kotlin.code.style>
    <kotlin.compiler.jvmTarget>1.8</kotlin.compiler.jvmTarget>

    <kotlin.version>1.9.22</kotlin.version>
  </properties>

  <repositories>
    <repository>
      <id>mavenCentral</id>
      <url>https://repo1.maven.org/maven2/</url>
    </repository>
  </repositories>

  <dependencies>
    <!-- KOTLIN -->
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib</artifactId>
      <version>${kotlin.version}</version>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-maven-allopen</artifactId>
      <version>${kotlin.version}</version>
    </dependency>

    <!-- API -->
    <dependency>
      <groupId>org.openapitools</groupId>
      <artifactId>openapi-generator-maven-plugin</artifactId>
      <version>7.9.0</version>
    </dependency>

    <!-- SPRING BOOT & RELATED -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <version>3.2.5</version>
      <exclusions>
        <exclusion>
          <groupId>ch.qos.logback</groupId>
          <artifactId>logback-classic</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>jakarta.annotation</groupId>
      <artifactId>jakarta.annotation-api</artifactId>
      <version>3.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jdbc</artifactId>
      <version>3.4.4</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-oauth2-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>

    <!-- DATASOURCE RELATED -->
    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
      <scope>runtime</scope>
      <version>8.0.33</version>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-reflect</artifactId>
      <version>${kotlin.version}</version>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib-jdk8</artifactId>
      <version>${kotlin.version}</version>
    </dependency>

    <!-- CAFFEINE -->
    <dependency>
      <groupId>com.github.ben-manes.caffeine</groupId>
      <artifactId>caffeine</artifactId>
      <version>3.2.2</version>
    </dependency>

    <!-- HTTP CLIENT -->
    <dependency>
      <groupId>org.apache.httpcomponents.client5</groupId>
      <artifactId>httpclient5</artifactId>
      <version>5.2.3</version>
    </dependency>

    <!-- GSON -->
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.11.0</version>
    </dependency>

    <!-- TEST -->
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>5.10.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-test-junit5</artifactId>
      <version>${kotlin.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <version>3.25.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-test</artifactId>
      <version>6.1.7</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.mockk</groupId>
      <artifactId>mockk-jvm</artifactId>
      <version>1.13.11</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.skyscreamer</groupId>
      <artifactId>jsonassert</artifactId>
      <version>1.5.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.github.tomakehurst</groupId>
      <artifactId>wiremock-standalone</artifactId>
      <version>3.0.1</version>
      <scope>test</scope>
    </dependency>
    <!-- TO REMOVE H2 -->
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <version>2.3.230</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <version>3.3.2</version>
      <scope>test</scope>
    </dependency>

    <!-- DOCKER -->
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>mysql</artifactId>
      <version>1.20.2</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <sourceDirectory>src/main/kotlin</sourceDirectory>
    <testSourceDirectory>src/test/kotlin</testSourceDirectory>
    <plugins>

      <plugin>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-maven-plugin</artifactId>
        <version>${kotlin.version}</version>
        <executions>
          <execution>
            <id>compile</id>
            <phase>compile</phase>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
          <execution>
            <id>test-compile</id>
            <phase>test-compile</phase>
            <goals>
              <goal>test-compile</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <compilerPlugins>
            <plugin>spring</plugin>
            <plugin>all-open</plugin>
          </compilerPlugins>
          <pluginOptions>
            <!-- Each annotation is placed on its own line -->
            <option>
              all-open:annotation=com.posadeus.fantatennis.app.configuration.infrastructure.OpenForSpring
            </option>
          </pluginOptions>
          <annotationProcessors>
            <annotation>org.springframework.transaction.annotation.Transactional</annotation>
            <annotation>org.springframework.context.annotation.Configuration</annotation>
          </annotationProcessors>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-maven-allopen</artifactId>
            <version>${kotlin.version}</version>
          </dependency>
        </dependencies>
      </plugin>

      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <executions>

          <execution>

            <id>GENERATE RANKING-API</id>

            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <generatorName>kotlin-spring</generatorName>
              <library>spring-boot</library>
              <inputSpec>${project.basedir}/src/main/resources/openApi-Ranking.yml</inputSpec>
              <generateSupportingFiles>false</generateSupportingFiles>
              <configOptions>
                <apiPackage>com.posadeus.fantatennis.controller</apiPackage>
                <modelPackage>com.posadeus.fantatennis.controller.model.ranking</modelPackage>
                <documentationProvider>none</documentationProvider>
                <exceptionHandler>false</exceptionHandler>
                <gradleBuildFile>false</gradleBuildFile>
                <interfaceOnly>true</interfaceOnly>
                <useBeanValidation>false</useBeanValidation>
                <useSpringBoot3>true</useSpringBoot3>
                <serializableModel>true</serializableModel>
                <skipDefaultInterface>true</skipDefaultInterface>
                <useTags>true</useTags>
              </configOptions>
            </configuration>
          </execution>

          <execution>

            <id>GENERATE PLAYER-API</id>

            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <generatorName>kotlin-spring</generatorName>
              <library>spring-boot</library>
              <inputSpec>${project.basedir}/src/main/resources/openApi-Player.yml</inputSpec>
              <generateSupportingFiles>false</generateSupportingFiles>
              <configOptions>
                <apiPackage>com.posadeus.fantatennis.controller</apiPackage>
                <modelPackage>com.posadeus.fantatennis.controller.model.player</modelPackage>
                <documentationProvider>none</documentationProvider>
                <exceptionHandler>false</exceptionHandler>
                <gradleBuildFile>false</gradleBuildFile>
                <interfaceOnly>true</interfaceOnly>
                <useBeanValidation>false</useBeanValidation>
                <useSpringBoot3>true</useSpringBoot3>
                <serializableModel>true</serializableModel>
                <skipDefaultInterface>true</skipDefaultInterface>
                <useTags>true</useTags>
              </configOptions>
            </configuration>
          </execution>

          <execution>

            <id>GENERATE TEAM-API</id>

            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <generatorName>kotlin-spring</generatorName>
              <library>spring-boot</library>
              <inputSpec>${project.basedir}/src/main/resources/openApi-Team.yml</inputSpec>
              <generateSupportingFiles>false</generateSupportingFiles>
              <configOptions>
                <apiPackage>com.posadeus.fantatennis.controller</apiPackage>
                <modelPackage>com.posadeus.fantatennis.controller.model.team</modelPackage>
                <documentationProvider>none</documentationProvider>
                <exceptionHandler>false</exceptionHandler>
                <gradleBuildFile>false</gradleBuildFile>
                <interfaceOnly>true</interfaceOnly>
                <useBeanValidation>false</useBeanValidation>
                <useSpringBoot3>true</useSpringBoot3>
                <serializableModel>true</serializableModel>
                <skipDefaultInterface>true</skipDefaultInterface>
                <useTags>true</useTags>
              </configOptions>
            </configuration>
          </execution>

          <execution>

            <id>GENERATE JOB-API</id>

            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <generatorName>kotlin-spring</generatorName>
              <library>spring-boot</library>
              <inputSpec>${project.basedir}/src/main/resources/openApi-Job.yml</inputSpec>
              <generateSupportingFiles>false</generateSupportingFiles>
              <configOptions>
                <apiPackage>com.posadeus.fantatennis.controller</apiPackage>
                <modelPackage>com.posadeus.fantatennis.controller.model.job</modelPackage>
                <documentationProvider>none</documentationProvider>
                <exceptionHandler>false</exceptionHandler>
                <gradleBuildFile>false</gradleBuildFile>
                <interfaceOnly>true</interfaceOnly>
                <useBeanValidation>false</useBeanValidation>
                <useSpringBoot3>true</useSpringBoot3>
                <serializableModel>true</serializableModel>
                <skipDefaultInterface>true</skipDefaultInterface>
                <useTags>true</useTags>
              </configOptions>
            </configuration>
          </execution>

          <execution>

            <id>GENERATE FANTA-TOURNAMENT-API</id>

            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <generatorName>kotlin-spring</generatorName>
              <library>spring-boot</library>
              <inputSpec>${project.basedir}/src/main/resources/openApi-FantaTournament.yml</inputSpec>
              <generateSupportingFiles>false</generateSupportingFiles>
              <configOptions>
                <apiPackage>com.posadeus.fantatennis.controller</apiPackage>
                <modelPackage>com.posadeus.fantatennis.controller.model.fantatournament</modelPackage>
                <documentationProvider>none</documentationProvider>
                <exceptionHandler>false</exceptionHandler>
                <gradleBuildFile>false</gradleBuildFile>
                <interfaceOnly>true</interfaceOnly>
                <useBeanValidation>false</useBeanValidation>
                <useSpringBoot3>true</useSpringBoot3>
                <serializableModel>true</serializableModel>
                <skipDefaultInterface>true</skipDefaultInterface>
                <useTags>true</useTags>
              </configOptions>
              <importMappings>
                TeamDto=com.posadeus.fantatennis.controller.model.team.TeamDto
              </importMappings>
              <typeMappings>
                object+teamDto=TeamDto
              </typeMappings>
            </configuration>
          </execution>

          <execution>

            <id>GENERATE TOURNAMENT-API</id>

            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <generatorName>kotlin-spring</generatorName>
              <library>spring-boot</library>
              <inputSpec>${project.basedir}/src/main/resources/openApi-Tournament.yml</inputSpec>
              <generateSupportingFiles>false</generateSupportingFiles>
              <configOptions>
                <apiPackage>com.posadeus.fantatennis.controller</apiPackage>
                <modelPackage>com.posadeus.fantatennis.controller.model.tournament</modelPackage>
                <documentationProvider>none</documentationProvider>
                <exceptionHandler>false</exceptionHandler>
                <gradleBuildFile>false</gradleBuildFile>
                <interfaceOnly>true</interfaceOnly>
                <useBeanValidation>false</useBeanValidation>
                <useSpringBoot3>true</useSpringBoot3>
                <serializableModel>true</serializableModel>
                <skipDefaultInterface>true</skipDefaultInterface>
                <useTags>true</useTags>
              </configOptions>
              <schemaMappings>
                PlayerPointsDto=com.posadeus.fantatennis.controller.model.team.PlayerPointsDto
              </schemaMappings>
              <importMappings>
                PlayerPointsDto=com.posadeus.fantatennis.controller.model.team.PlayerPointsDto
              </importMappings>
            </configuration>
          </execution>

        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <executions>
          <execution>
            <id>fix-players-swap-dto-defaults</id>
            <phase>process-sources</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <replaceregexp
                  file="${project.build.directory}/generated-sources/openapi/src/main/kotlin/com/posadeus/fantatennis/controller/model/team/PlayersToSwapDto.kt"
                  match="val remove: PlayersToRemoveDto"
                  replace="val remove: PlayersToRemoveDto = PlayersToRemoveDto()"/>
                <replaceregexp
                  file="${project.build.directory}/generated-sources/openapi/src/main/kotlin/com/posadeus/fantatennis/controller/model/team/PlayersToSwapDto.kt"
                  match="val add: PlayersToAddDto"
                  replace="val add: PlayersToAddDto = PlayersToAddDto()"/>
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>

    </plugins>
  </build>

</project>