spring:
  application:
    name: fanta-tennis

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
        security: DEBUG

server:
  servlet:
    context-path: /fanta-tennis

client:
  atp-tour:
    uri: https://www.atptour.com
    http:
      connection-timeout: 2000
      connection-request-timeout: 2000

  tennis-tv:
    uri: https://api.tennistv.com/tennis
    http:
      connection-timeout: 2000
      connection-request-timeout: 2000

  wimbledon:
    uri: https://www.wimbledon.com
    http:
      connection-timeout: 2000
      connection-request-timeout: 2000

  us-open:
    uri: https://www.usopen.org
    http:
      connection-timeout: 2000
      connection-request-timeout: 2000

  aus-open:
    uri: https://prod-scores-api.ausopen.com
    http:
      connection-timeout: 2000
      connection-request-timeout: 2000

  roland-garros:
    uri: https://www.rolandgarros.com
    http:
      connection-timeout: 2000
      connection-request-timeout: 2000

# Duration is always in minutes
# 6h = 360m
# 24h = 1440m
# 7d  = 10080m
caches:
  caffeine:
    tournaments-cache:
      expire-after-write-duration: 1440
      expire-after-access-duration: 1440
      maximum-size: 300
    tournament-cache:
      expire-after-write-duration: 1440
      expire-after-access-duration: 1440
      maximum-size: 300
    player-cache:
      expire-after-write-duration: 10080
      maximum-size: 1000
    players-points-by-tournament-id-cache:
      expire-after-write-duration: 360
      maximum-size: 1000
    players-points-by-tournament-year-cache:
      expire-after-write-duration: 360
      maximum-size: 1000
    fanta-team-cache:
      expire-after-write-duration: 10080
      expire-after-access-duration: 10080
      maximum-size: 1000
    fanta-tournament-cache:
      expire-after-write-duration: 10080
      expire-after-access-duration: 10080
      maximum-size: 1000
    fanta-tournaments-cache:
      expire-after-write-duration: 10080
      expire-after-access-duration: 10080
      maximum-size: 1000
    fanta-tournament-team-by-tournament-id-cache:
      expire-after-write-duration: 10080
      maximum-size: 1000