spring:
  application:
    name: fanta-tennis

  datasource:
    url: jdbc:mysql://localhost:3306/fanta_tennis
    username: root
    password: RogerFederer81
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG

server:
  servlet:
    context-path: /fanta-tennis

client:
  atp-tour:
    uri: https://www.atptour.com
    http:
      connection-timeout: 2000
      connection-request-timeout: 2000

  tennis-tv:
    uri: https://api.tennistv.com/tennis
    http:
      connection-timeout: 2000
      connection-request-timeout: 2000

  wimbledon:
    uri: https://www.wimbledon.com
    http:
      connection-timeout: 2000
      connection-request-timeout: 2000

  us-open:
    uri: https://www.usopen.org
    http:
      connection-timeout: 2000
      connection-request-timeout: 2000

  aus-open:
    uri: https://prod-scores-api.ausopen.com
    http:
      connection-timeout: 2000
      connection-request-timeout: 2000