components:
  schemas:

    RankedPlayerDto:
      type: object
      properties:
        id:
          type: string
          default: 0
          description: Player's unique ID
        fullName:
          type: string
          default: ""
          description: Player's name
        rank:
          type: integer
          description: Player's ranking
        points:
          type: integer
          description: Player's points
      required:
        - id
        - fullName
        - rank
        - points

    TeamDto:
      type: object
      properties:
        owner:
          type: string
          default: ""
          description: The owner of the team
        players:
          $ref: '#/components/schemas/PlayersPointsDto'
        totalScore:
          type: double
          default: 0
          description: Total team's score
      required:
        - owner
        - players
        - totalScore

    PlayersPointsDto:
      type: array
      items:
        $ref: '#/components/schemas/PlayerPointsDto'

    PlayerPointsDto:
      type: object
      properties:
        fullName:
          type: string
          default: ""
          description: Player's full name
        fantaPoints:
          type: double
          default: 0
          description: Player's fanta-points
      required:
        - fullName
        - fantaPoints

    TeamCreatedDto:
      type: object
      properties:
        id:
          type: integer
          default: 0
          description: Team ID
        ownerId:
          type: string
          default: ""
          description: Team's Owner ID
      required:
        - id
        - ownerId

    TeamToCreateDto:
      type: object
      properties:
        tournamentId:
          type: integer
          default: 0
      required:
        - tournamentId

    PlayersToAddDto:
      type: object
      properties:
        playerIds:
          type: array
          default: [ ]
          items:
            type: string
          uniqueItems: true
        startingTournamentId:
          type: integer
          default: 0
          example: 1
      example:
        playerIds: [ "id1", "id2", "id3" ]
        startingTournamentId: 1
      required:
        - playerIds
        - startingTournamentId

    PlayersToRemoveDto:
      type: object
      properties:
        playerIds:
          type: array
          default: [ ]
          items:
            type: string
          uniqueItems: true
        endingTournamentId:
          type: integer
          default: 0
          example: 1
      example:
        playerIds: [ "id1", "id2", "id3" ]
        endingTournamentId: 1
      required:
        - playerIds
        - endingTournamentId

    PlayersToSwapDto:
      type: object
      x-class-extra-annotation: "@com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = com.posadeus.fantatennis.app.configuration.controller.PlayersToSwapDtoDeserializer::class)"
      properties:
        remove:
          $ref: '#/components/schemas/PlayersToRemoveDto'
        add:
          $ref: '#/components/schemas/PlayersToAddDto'
      required:
        - remove
        - add

    FantaTournamentDto:
      type: object
      properties:
        teams:
          $ref: '#/components/schemas/TeamsDto'
      required:
        - teams

    TeamsDto:
      type: array
      items:
        type: object
        format: teamDto

    FantaTournamentToCreateDto:
      type: object
      properties:
        startingTournamentId:
          type: integer
          example: 1
          default: 1
        endingTournamentId:
          type: integer
          example: 1
          default: 1
        tournamentYear:
          type: integer
          example: 2024
          default: 2024
      required:
        - startingTournamentId
        - endingTournamentId
        - tournamentYear

    FantaTournamentCreatedDto:
      type: object
      properties:
        id:
          type: integer
          example: 1
        startingTournamentId:
          type: integer
          example: 1
        endingTournamentId:
          type: integer
          example: 1
        tournamentYear:
          type: integer
          example: 2024
      required:
        - id
        - startingTournamentId
        - endingTournamentId
        - tournamentYear

    FantaTournamentsDto:
      type: object
      properties:
        ids:
          type: array
          items:
            type: integer

    JobSucceedWithErrorsDto:
      type: object
      properties:
        message:
          type: string
      required:
        - message

    TournamentDto:
      type: object
      properties:
        tournamentName:
          type: string
        tournamentPoints:
          type: integer
        playersScore:
          $ref: '#/components/schemas/PlayersPointsDto'
      required:
        - tournamentName
        - tournamentPoints
        - playersScore

    TournamentsDto:
      type: object
      properties:
        tournaments:
          type: array
          items:
            $ref: '#/components/schemas/TournamentDto'
      required:
        - tournaments
