openapi: 3.0.0
info:
  title: API to update data with scheduled jobs
  version: 1.0.0
paths:
  /job/points/{tournamentId}/{year}:
    post:
      operationId: updatePlayersFantaPoints
      summary: Update Players fanta points
      description: Update Players fanta points
      tags:
        - Job
      parameters:
        - in: path
          name: tournamentId
          schema:
            type: integer
          required: true
          description: Tournament's unique ID to update.
        - in: path
          name: year
          schema:
            type: integer
          required: true
          description: Year to update.
      responses:
        '204':
          description: Players fanta points updated successfully
        '400':
          description: Wrong input params
        '500':
          description: Error during the process
  /job/tournaments/{year}:
    post:
      operationId: addTournamentsForYear
      summary: Add Tournaments to DB for a specific year
      description: Add Tournaments to DB for a specific year
      tags:
        - Job
      parameters:
        - in: path
          name: year
          schema:
            type: integer
          required: true
          description: Year to take tournaments
      responses:
        '204':
          description: Tournaments added correctly
        '400':
          description: Wrong input params
        '500':
          description: Error during the process