openapi: 3.0.0
info:
  title: Team
  version: 1.0.0
paths:
  /team/{teamId}:
    get:
      operationId: retrieve
      summary: Returns your team players
      description: Returns an ordered list based on your player points.
      tags:
        - Team
      parameters:
        - in: path
          name: teamId
          schema:
            type: integer
          required: true
          description: ID of the team
      responses:
        '200':
          description: Team found
          content:
            application/json:
              schema:
                $ref: './openApi-schemas.yml#/components/schemas/TeamDto'
        '500':
          description: Error during team retrieval

  /team:
    post:
      operationId: create
      summary: Create a team.
      description: Create an empty team.
      tags:
        - Team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openApi-schemas.yml#/components/schemas/TeamToCreateDto'
      responses:
        '201':
          description: Team created
          content:
            application/json:
              schema:
                $ref: './openApi-schemas.yml#/components/schemas/TeamCreatedDto'
        '400':
          description: Wrong input body
        '500':
          description: Error during team retrieval

  /team/{teamId}/players/add:
    post:
      operationId: addPlayers
      summary: Add players to an existing team.
      description: Add players to and existing team.
      tags:
        - Team
      parameters:
        - in: path
          name: teamId
          schema:
            type: integer
          required: true
          description: ID of the team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openApi-schemas.yml#/components/schemas/PlayersToAddDto'
      responses:
        '200':
          description: IDs processed successfully and players added to the team
          content:
            application/json:
              schema:
                $ref: './openApi-schemas.yml#/components/schemas/TeamDto'
        '400':
          description: Wrong input body
        '500':
          description: Error during team update

  /team/{teamId}/players/swap:
    post:
      operationId: swap
      summary: Swap players for an existing team.
      description: Swap one or more players for an existing team.
      tags:
        - Team
      parameters:
        - in: path
          name: teamId
          schema:
            type: integer
          required: true
          description: ID of the team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openApi-schemas.yml#/components/schemas/PlayersToSwapDto'
      responses:
        '204':
          description: IDs processed successfully and players swapped for the team
        '400':
          description: Wrong input body
        '500':
          description: Error during team update