openapi: 3.0.0
info:
  title: Fanta Tournament
  version: 1.0.0
paths:
  /fanta-tournament/{tournamentId}:
    get:
      operationId: retrieve
      summary: Returns a Fanta Tournament by its ID
      description: Returns an ordered list based on your team points.
      tags:
        - FantaTournament
      parameters:
        - in: path
          name: tournamentId
          schema:
            type: integer
          required: true
          description: ID of the tournament
      responses:
        '200':
          description: Fanta Tournament found
          content:
            application/json:
              schema:
                $ref: './openApi-schemas.yml#/components/schemas/FantaTournamentDto'
        '400':
          description: Not found tournament ID
        '500':
          description: Error during tournament retrieval

  /fanta-tournament:
    post:
      operationId: create
      summary: Create a Fanta Tournament.
      description: Create an empty Tournament.
      tags:
        - FantaTournament
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openApi-schemas.yml#/components/schemas/FantaTournamentToCreateDto'
      responses:
        '201':
          description: Fanta Tournament created
          content:
            application/json:
              schema:
                $ref: './openApi-schemas.yml#/components/schemas/FantaTournamentCreatedDto'
        '400':
          description: Wrong input body
        '500':
          description: Error during tournament retrieval

  /fanta-tournaments:
    get:
      operationId: retrieveAll
      summary: Returns all the Fanta Tournaments
      description: Returns the list of all Fanta Tournaments.
      tags:
        - FantaTournament
      responses:
        '200':
          description: Fanta Tournaments found
          content:
            application/json:
              schema:
                $ref: './openApi-schemas.yml#/components/schemas/FantaTournamentsDto'
        '404':
          description: Not found tournament ID
        '500':
          description: Error during tournaments retrieval