openapi: 3.0.0
info:
  title: Team
  version: 1.0.0
paths:
  /team/{teamId}:
    get:
      operationId: retrieve
      summary: Returns your team players
      description: Returns an ordered list based on your player points.
      tags:
        - Team
      parameters:
        - in: path
          name: teamId
          schema:
            type: integer
          required: true
          description: ID of the team
      responses:
        '200':
          description: Team found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamDto'
        '500':
          description: Error during team retrieval

  /team:
    post:
      operationId: create
      summary: Create a team.
      description: Create an empty team.
      tags:
        - Team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamToCreateDto'
      responses:
        '201':
          description: Team created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamCreatedDto'
        '400':
          description: Wrong input body
        '500':
          description: Error during team retrieval

  /team/{teamId}/players:
    post:
      operationId: addPlayers
      summary: Add players to an existing team.
      description: Create an empty team.
      tags:
        - Team
      parameters:
        - in: path
          name: teamId
          schema:
            type: integer
          required: true
          description: ID of the team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayersToAddDto'
      responses:
        '200':
          description: IDs processed successfully and players added to the team
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamDto'
        '400':
          description: Wrong input body
        '500':
          description: Error during team update

components:
  schemas:
    TeamDto:
      type: object
      properties:
        players:
          $ref: '#/components/schemas/TeamPlayersDto'
        totalScore:
          type: double
          default: 0
          description: Total team's score
      required:
        - players
        - totalScore

    TeamPlayersDto:
      type: array
      items:
        $ref: '#/components/schemas/TeamPlayerDto'

    TeamPlayerDto:
      type: object
      properties:
        fullName:
          type: string
          default: ""
          description: Player's full name
        fantaPoints:
          type: double
          default: 0
          description: Player's fanta-points
      required:
        - fullName
        - fantaPoints

    TeamCreatedDto:
      type: object
      properties:
        id:
          type: integer
          default: 0
          description: Team ID
        ownerId:
          type: string
          default: ""
          description: Team's Owner ID
      required:
        - id
        - ownerId

    TeamToCreateDto:
      type: object
      properties:
        ownerId:
          type: string
          default: ""
          example: OWNER_ID
        tournament:
          $ref: '#/components/schemas/TournamentCreationDto'
      required:
        - ownerId
        - tournament

    PlayersToAddDto:
      type: object
      properties:
        playerIds:
          type: array
          default: [ ]
          items:
            type: string
          uniqueItems: true
      example:
        playerIds: [ "id1", "id2", "id3" ]
      required:
        - playerIds

    TournamentCreationDto:
      type: object
      properties:
        id:
          type: integer
          example: 1
        startingTournament:
          type: integer
          example: 1
        endingTournament:
          type: integer
          example: 1
        tournamentYear:
          type: integer
          example: 2024
      required:
        - id