/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.posadeus.controller

import com.posadeus.controller.model.player.Player
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestMethod

@RequestMapping("\${api.base-path:}")
interface PlayerApi {

  @RequestMapping(
      method = [RequestMethod.GET],
      value = ["/player/{id}"],
      produces = ["application/json"]
  )
  fun player(@PathVariable("id") id: Int): ResponseEntity<Player>
}
