-- fanta_tennis.TOURNAMENTS definition
CREATE TABLE `TOURNAMENTS` (
  `TOURNAMENT_ID` int NOT NULL AUTO_INCREMENT,
  `ATP_TOUR_ID` int NOT NULL,
  `TENNIS_TV_ID` int NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `POINTS` int NOT NULL,
  `LOCATION` varchar(100) NOT NULL,
  `SURFACE` enum('HARD','CLAY','GRASS') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `YEAR` int NOT NULL,
  `START_DATE` date NOT NULL DEFAULT '2024-01-01',
  `END_DATE` date NOT NULL DEFAULT '2024-01-01',
  PRIMARY KEY (`TOURNAMENT_ID`),
  UNIQUE KEY `TOURNAMENTS_UNIQUE` (`ATP_TOUR_ID`,`TENNIS_TV_ID`,`NAME`,`YEAR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- fanta_tennis.FANTA_TOURNAMENTS definition
CREATE TABLE `FANTA_TOURNAMENTS` (
  `FANTA_TOURNAMENT_ID` int NOT NULL AUTO_INCREMENT,
  `STARTING_TOURNAMENT` int NOT NULL,
  `ENDING_TOURNAMENT` int NOT NULL,
  `TOURNAMENT_YEAR` int NOT NULL,
  PRIMARY KEY (`FANTA_TOURNAMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- fanta_tennis.FANTA_TEAMS definition
CREATE TABLE `FANTA_TEAMS` (
  `TEAM_ID` int NOT NULL AUTO_INCREMENT,
  `OWNER_ID` varchar(100) NOT NULL,
  PRIMARY KEY (`TEAM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- fanta_tennis.FANTA_TOURNAMENTS_TEAMS definition
CREATE TABLE `FANTA_TOURNAMENTS_TEAMS` (
  `FANTA_TOURNAMENT_ID` int NOT NULL,
  `TEAM_ID` int NOT NULL,
  PRIMARY KEY (`FANTA_TOURNAMENT_ID`,`TEAM_ID`),
  KEY `FANTA_TOURNAMENTS_TEAMS_FANTA_TEAMS_FK` (`TEAM_ID`),
  CONSTRAINT `FANTA_TOURNAMENTS_TEAMS_FANTA_TEAMS_FK` FOREIGN KEY (`TEAM_ID`) REFERENCES `FANTA_TEAMS` (`TEAM_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FANTA_TOURNAMENTS_TEAMS_FANTA_TOURNAMENTS_FK` FOREIGN KEY (`FANTA_TOURNAMENT_ID`) REFERENCES `FANTA_TOURNAMENTS` (`FANTA_TOURNAMENT_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- fanta_tennis.PLAYERS definition
CREATE TABLE `PLAYERS` (
  `PLAYER_ID` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `ATP_TOUR_ID` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `FULL_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `RG_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`PLAYER_ID`),
  UNIQUE KEY `PLAYERS_UNIQUE` (`ATP_TOUR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- fanta_tennis.PLAYERS_POINTS definition
CREATE TABLE `PLAYERS_POINTS` (
  `TOURNAMENT_YEAR` int NOT NULL,
  `TOURNAMENT_ID` int NOT NULL,
  `PLAYER_ID` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `FANTA_POINTS` decimal(8,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`TOURNAMENT_YEAR`,`TOURNAMENT_ID`,`PLAYER_ID`),
  KEY `PLAYERS_POINTS_PLAYERS_FK` (`PLAYER_ID`),
  KEY `PLAYERS_POINTS_TOURNAMENTS_FK` (`TOURNAMENT_ID`),
  CONSTRAINT `PLAYERS_POINTS_PLAYERS_FK` FOREIGN KEY (`PLAYER_ID`) REFERENCES `PLAYERS` (`PLAYER_ID`),
  CONSTRAINT `PLAYERS_POINTS_TOURNAMENTS_FK` FOREIGN KEY (`TOURNAMENT_ID`) REFERENCES `TOURNAMENTS` (`TOURNAMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- fanta_tennis.TEAMS definition
CREATE TABLE `TEAMS` (
  `TEAM_ID` int NOT NULL,
  `PLAYER_ID` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `STARTING_TOURNAMENT` int NOT NULL DEFAULT '1',
  `ENDING_TOURNAMENT` int DEFAULT NULL,
  PRIMARY KEY (`TEAM_ID`,`PLAYER_ID`,`STARTING_TOURNAMENT`),
  KEY `TEAMS_PLAYERS_FK` (`PLAYER_ID`),
  KEY `TEAMS_TOURNAMENTS_FK` (`STARTING_TOURNAMENT`),
  KEY `TEAMS_TOURNAMENTS_FK_1` (`ENDING_TOURNAMENT`),
  CONSTRAINT `TEAMS_FANTA_TEAMS_FK` FOREIGN KEY (`TEAM_ID`) REFERENCES `FANTA_TEAMS` (`TEAM_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `TEAMS_PLAYERS_FK` FOREIGN KEY (`PLAYER_ID`) REFERENCES `PLAYERS` (`PLAYER_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `TEAMS_TOURNAMENTS_FK` FOREIGN KEY (`STARTING_TOURNAMENT`) REFERENCES `TOURNAMENTS` (`TOURNAMENT_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `TEAMS_TOURNAMENTS_FK_1` FOREIGN KEY (`ENDING_TOURNAMENT`) REFERENCES `TOURNAMENTS` (`TOURNAMENT_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
